<?php

namespace Eden\Instagram;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-09 at 21:07:44.
 */
class EndpointTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Endpoint
     */
    protected $endpoint;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->endpoint = eden('instagram')->endpoint('<TOKEN>');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Eden\Instagram\Endpoint::comment
     */
    public function testComment()
    {
        $obj = $this->endpoint
                ->comment();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Comment', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::geography
     */
    public function testGeography()
    {
        $obj = $this->endpoint
                ->geography();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Geography', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::like
     */
    public function testLike()
    {
        $obj = $this->endpoint
                ->like();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Like', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::location
     */
    public function testLocation()
    {
        $obj = $this->endpoint
                ->location();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Location', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::media
     */
    public function testMedia()
    {
        $obj = $this->endpoint
                ->media();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Media', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::relationship
     */
    public function testRelationship()
    {
        $obj = $this->endpoint
                ->relationship();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Relationship', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::tag
     */
    public function testTag()
    {
        $obj = $this->endpoint
                ->tag();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\Tag', $obj);
    }

    /**
     * @covers Eden\Instagram\Endpoint::user
     */
    public function testUser()
    {
        $obj = $this->endpoint
                ->user();
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint\\User', $obj);
    }

}
