<?php

namespace Eden\Instagram;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-09 at 21:07:29.
 */
class FactoryTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Factory
     */
    protected $factory;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->factory = eden('instagram');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Eden\Instagram\Factory::auth
     */
    public function testAuth()
    {
        $auth = $this->factory
                ->auth('1234567890', '1234567890', 'http://localhost/');
        $this->assertInstanceOf('Eden\\Instagram\\Auth', $auth);
    }

    /**
     * @covers Eden\Instagram\Factory::endpoint
     */
    public function testEndpoint()
    {
        $endpoint = $this->factory
                ->endpoint('<TOKEN>');
        $this->assertInstanceOf('Eden\\Instagram\\Endpoint', $endpoint);
    }

}
