<?php

namespace Eden\Instagram\Endpoint;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-10 at 02:33:36.
 */
class RelationshipTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Relationship
     */
    protected $key = '';
    protected $secret = '';
    protected $redirect = '';
    protected $code = '';
    protected $token = '';
    protected $relationship;
    protected $userId = 0;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        if (!empty($this->token)) {
            $this->relationship = eden('instagram')
                    ->endpoint($this->token)
                    ->relationship();
        }
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    public function testCode()
    {
        if (empty($this->code) && empty($this->token)) {
            $scope = array(
                'basic',
                'comments',
                'relationships',
                'likes'
            );

            $url = eden('instagram')
                    ->auth($this->key, $this->secret, $this->redirect)
                    ->getLoginUrl($scope);

            $this->assertTrue(false, 'Please login to this url: ' . $url);
        }
    }

    public function testToken()
    {
        if (empty($this->code) || empty($this->token)) {
            $auth = eden('instagram')
                    ->auth($this->key, $this->secret, $this->redirect);

            $accessToken = $auth->getAccess($this->code);

            if (isset($accessToken['access_token'])) {
                $this->assertTrue(false,
                                  'Your access token: ' . $accessToken['access_token']);
            } else {
                $meta = $auth->getMeta();

                $url = $meta['url'];
                $url .= '?' . http_build_query($meta['query']);

                $this->assertTrue(false,
                                  'Put the access code and get the access token from this: ' . $url);
            }
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::getFollows
     */
    public function testGetFollows()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId(3)
                ->getFollows();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::getFollowedBy
     */
    public function testGetFollowedBy()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->getFollowedBy();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::getRequestedBy
     */
    public function testGetRequestedBy()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship
                ->getRequestedBy();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::getRelationship
     */
    public function testGetRelationship()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->getRelationship();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::follow
     */
    public function testFollow()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->follow();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::unfollow
     */
    public function testUnfollow()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->unfollow();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::block
     */
    public function testBlock()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->block();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::Unblock
     */
    public function testUnblock()
    {
        if (empty($this->token)) {
            return;
        }

        $response = $this->relationship->setId($this->userId)
                ->unblock();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::approve
     */
    public function testApprove()
    {
        $response = $this->relationship->setId($this->userId)
                ->approve();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

    /**
     * @covers Eden\Instagram\Endpoint\Relationship::ignore
     */
    public function testIgnore()
    {
        $response = $this->relationship->setId($this->userId)
                ->ignore();
        
        if (!is_array($response)) {
            $this->assertTrue($response === null);
        } else if (isset($response['meta']['error_message'])) {
            $this->assertTrue(false, $response['meta']['error_message']);
        } else {
            $this->assertArrayHasKey('data', $response);
        }
    }

}
